<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_UG HOME SCIENCE ADMISSION - 2024_lazy</name>
   <tag></tag>
   <elementGuidId>2ed10713-ea3e-4271-928a-886a024b604f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.lazy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[4]/div/div/div/div/div/figure/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.lazy >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>dc4ef3f9-7614-4d62-b12c-ee49849adbfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>01ed58ae-3aac-48e4-b9c8-4be8ebe3d434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/round_pic2.jpg</value>
      <webElementGuid>ac62544b-928d-4d0a-81f2-cbee121e18e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>159</value>
      <webElementGuid>32eb5b50-6bcc-4d9f-8f7c-5ade78a14e86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>161</value>
      <webElementGuid>2949f2e9-f481-46de-9c78-2f4935b90ad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;main_contain&quot;]/div[@class=&quot;top_list_sec&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row colm_list_top&quot;]/div[@class=&quot;col-sm-12 c col-md-4 colm_list&quot;]/div[@class=&quot;colm_list_in&quot;]/figure[1]/img[@class=&quot;lazy&quot;]</value>
      <webElementGuid>b6f5fabd-a582-44fa-be71-9c2c804927a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/figure/img</value>
      <webElementGuid>6e4e54df-9592-403c-bb3e-dd87dbebbdaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'images/round_pic2.jpg']</value>
      <webElementGuid>e842ffab-8b05-404d-875d-48d5c9ce4dc1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
