<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Grievance Cell for Reserved Category_lazy</name>
   <tag></tag>
   <elementGuidId>2427247e-199c-496d-a699-dfe3068de96f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[4]/div/div/div/div[3]/div/figure/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(3) > .colm_list_in > figure > .lazy</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c49d367e-8792-47cf-b1f6-cf5d68d033f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>4fb5c352-a8bb-447d-b477-f4b9b02449a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/round_pic3.jpg</value>
      <webElementGuid>cad15446-0357-4112-a27e-9cae002f6bd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>159</value>
      <webElementGuid>37632587-1d9c-4fd0-adab-2ae94294fdfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>161</value>
      <webElementGuid>45e6b0a5-0b0f-4d5c-a4ed-582dd5a816a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;main_contain&quot;]/div[@class=&quot;top_list_sec&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row colm_list_top&quot;]/div[@class=&quot;col-sm-12 c col-md-4 colm_list&quot;]/div[@class=&quot;colm_list_in&quot;]/figure[1]/img[@class=&quot;lazy&quot;]</value>
      <webElementGuid>63fea11f-7cf3-4909-99b7-f1c112b4609b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[3]/div/figure/img</value>
      <webElementGuid>8b0624b1-f61f-456c-8bc3-a5fa0a10a732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'images/round_pic3.jpg']</value>
      <webElementGuid>3fa5c5fa-af1b-4dc3-94a2-8b2aeab2f5d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
