<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Scholarship_lazy</name>
   <tag></tag>
   <elementGuidId>842a06b7-b693-4228-989b-90efbeeb54ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[4]/div/div/div/div[2]/div/figure/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(2) > .colm_list_in > figure > .lazy</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d6dad413-f85d-4557-aa12-1226c64c7bf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>befd1f8c-ff25-45ce-9624-1a8655091bdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/round_pic1.jpg</value>
      <webElementGuid>2aca0b8d-1d0f-474d-a277-0a99eb16f14c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>159</value>
      <webElementGuid>79838c42-4c13-41a4-80eb-d868016758bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>161</value>
      <webElementGuid>75d3203a-aec6-4703-8acc-746344fad0e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;main_contain&quot;]/div[@class=&quot;top_list_sec&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row colm_list_top&quot;]/div[@class=&quot;col-sm-12 c col-md-4 colm_list&quot;]/div[@class=&quot;colm_list_in&quot;]/figure[1]/img[@class=&quot;lazy&quot;]</value>
      <webElementGuid>2e1b8cc2-a563-4bda-afc2-5160f9b14b88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]/div/figure/img</value>
      <webElementGuid>d9ef741c-4a43-41b7-8f35-5b1a2393ad2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'images/round_pic1.jpg']</value>
      <webElementGuid>7375e475-387a-4e7f-886a-92593c39d4f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
