<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Horticulture</name>
   <tag></tag>
   <elementGuidId>e6355014-acec-4cfd-8079-1572cd7f7c6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Agricultural']/div/div/div/div[2]/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Horticulture&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e781d95f-e524-457f-8b80-6b1fa3f2a6b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Horticulture.html</value>
      <webElementGuid>9056c306-7fda-4b90-94df-51185614e7d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Horticulture</value>
      <webElementGuid>5866c268-5c09-46ac-888b-9348a85688f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Agricultural&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;mx-auto content_wrapper_cont&quot;]/div[@class=&quot;content_panel&quot;]/div[@class=&quot;content_box&quot;]/ul[1]/li[2]/a[1]</value>
      <webElementGuid>f690082f-a471-431e-8cc0-4ed239f63c91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Agricultural']/div/div/div/div[2]/ul/li[2]/a</value>
      <webElementGuid>17b85e8b-6b69-4ab1-b9cd-840d178de96c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Horticulture')]</value>
      <webElementGuid>827d4078-257f-4398-a462-7dc700c1fb6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Plant Physiology'])[1]/following::a[1]</value>
      <webElementGuid>52093b0e-b8bb-4b10-9f83-ac63c384d579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Genetics &amp; Plant Breeding'])[1]/following::a[2]</value>
      <webElementGuid>72b11ab8-14b9-41d6-8c30-1dd1aca26c62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seed Science &amp; Technology'])[1]/preceding::a[1]</value>
      <webElementGuid>8946c2e9-e8fe-4dd4-a2e3-271ef49f77fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Faculty Council for Post-Graduate Studies in Arts'])[1]/preceding::a[2]</value>
      <webElementGuid>639903f7-c2c2-402a-9901-624a58a0be63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Horticulture']/parent::*</value>
      <webElementGuid>6f9580aa-b667-4915-99a2-ababf2fc5b70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'Horticulture.html')]</value>
      <webElementGuid>ba1409bd-b52a-4f38-bc7c-d9b62a78fbcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/ul/li[2]/a</value>
      <webElementGuid>7e8e2e2e-5413-44f9-a39b-ae3aff1dda4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'Horticulture.html' and (text() = 'Horticulture' or . = 'Horticulture')]</value>
      <webElementGuid>f9ad180c-ac59-4c85-9f86-5d7c694107ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
