<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>e6eeea1d-e763-4320-af30-25fbe123ec05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.card > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.card > img >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b0edd073-2585-4eb8-99b1-7ee7649b37c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/ac-bnr-1.jpg</value>
      <webElementGuid>95edd502-ea42-4e35-9eec-554077231c35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/section[@class=&quot;inner_page_section academy_page&quot;]/section[@class=&quot;ac-zigzag-bnr&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;card-columns&quot;]/div[@class=&quot;single-card&quot;]/div[@class=&quot;card&quot;]/img[1]</value>
      <webElementGuid>d95cc7de-7b3b-4063-9c7b-0c6ddded6309</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>29108245-cc4b-44de-9e9e-7bf622c5d0b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'images/ac-bnr-1.jpg']</value>
      <webElementGuid>f39e53b6-53a7-4c2f-8fe1-9c09a237a69a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
